version: '3.1'

services:

  postgres:
    image: postgres:latest
    container_name: my_postgres
    ports:
      - "5432:5432"
    volumes:
      - postgresvol:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pg-admin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    depends_on:
      - postgres

  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8200:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_BASICAUTH=false
    depends_on:
      - mongo

  mysql-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - mysqlvol:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8201:8080
    depends_on:
      - mysql-db

  redis:
    image: redis:latest
    container_name: my_redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: my_rabbit
    ports:
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 123456

volumes:
  postgresvol:
    driver: local
  mysqlvol:
    driver: local