server:
  port: 8089

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/v1/customers/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
        - id: advertisement-service
          uri: lb://ADVERTISEMENT-SERVICE
          predicates:
            - Path=/api/v1/advertisements/**
        - id: package-service
          uri: lb://PACKAGE-SERVICE
          predicates:
            - Path=/api/v1/packages/**
        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/notifications/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
        - id: purchase-service
          uri: lb://PURCHASE-SERVICE
          predicates:
            - Path=/api/v1/purchases/**
