server:
  port: 8089

spring:
  application:
    name: gateway
    security:
      jwt:
        secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
        expiration: 86400000
        refresh-token:
          expiration: 604800000

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/auth/**
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/v1/customers/**
          filters:
            - AuthenticationFilter
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
          filters:
            - AuthenticationFilter
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - AuthenticationFilter
        - id: purchase-service
          uri: lb://PURCHASE-SERVICE
          predicates:
            - Path=/api/v1/purchases/**
          filters:
            - AuthenticationFilter
        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - AuthenticationFilter
        - id: cpackage-service
          uri: lb://CPACKAGE-SERVICE
          predicates:
            - Path=/api/v1/packages/**
          filters:
            - AuthenticationFilter
        - id: advertisement-service
          uri: lb://ADVERTISEMENT-SERVICE
          predicates:
            - Path=/api/v1/advertisements/**
          filters:
            - AuthenticationFilter